[transformation] Multiple Target Assignment
JetBrains-Research/ast-transformations pull request #13
Opened 2020-11-04 09:50 UTC by artbobrov

2020-11-09 19:43 UTC, nbirillo requested changes
Great job, but I have a small comment

2020-11-09 19:43 UTC, nbirillo commented on src/test/kotlin/org/jetbrains/research/ml/ast/transformations/util/TransformationsTest.kt
> +        }
you use this fragment of code twice. Let's refactor a little bit:
```
protected fun getPsiFile(file: File, toReformatFile: Bolean = true): PsiFile {
        val psiFile = myFixture.configureByFile(file.path)
       if (toReformatFile) {
              WriteCommandAction.runWriteCommandAction(project) { // reformat the expected file
                   codeStyleManager.reformat(psiFile)
               }
       }
        return psiFile
    }
```

```
        ...
        val psiInFile = getPsiFile(inFile)
        val expectedPsiInFile = getPsiFile(outFile)
        ...
```

Moreover, you can call the `getPsiFile` method in the `PsiTreeConverterTest` class:

https://github.com/nbirillo/ast-transformations/blob/master/src/test/kotlin/org/jetbrains/research/ml/ast/gumtree/tree/PsiTreeConverterTest.kt#L56

Here, we get the relative path maybe not the best way. We can delete it and use `file.path`

2020-11-11 16:32 UTC, nbirillo commented on src/test/resources/org/jetbrains/research/ml/ast/transformations/multipleTargetAssignment/data/in_2.py
> +    c = None
What shows this test?

2020-11-11 16:50 UTC, artbobrov commented on src/test/resources/org/jetbrains/research/ml/ast/transformations/multipleTargetAssignment/data/in_2.py
> +    c = None
Not to target simple expressions.

2020-11-11 17:10 UTC, nbirillo approved these changes
Great!

2020-11-18 13:23 UTC, elena-lyulina approved these changes
Cool!

2020-11-18 13:25 UTC, merged