[transformation] Anonymization
JetBrains-Research/ast-transformations pull request #15
Opened 2020-11-16 05:33 UTC by shananton

2020-11-16 12:18 UTC, nbirillo requested changes
It looks totally great! Thank you!

2020-11-16 12:18 UTC, nbirillo commented on docs/Anonymization.md
> +    | Prefix | Kind                    |
Please, add an empty line before the table

2020-11-16 12:18 UTC, nbirillo commented on docs/Anonymization.md
> +  Note: lambda expressions do not have a name, thus cannot be renamed. However,
Please, add an empty line after the table

2020-11-16 12:18 UTC, nbirillo commented on docs/Anonymization.md
> +  (i. e. have the same name as a builtin and are global) are not renamed.
I am not sure about this point. Maybe should we rename?

2020-11-16 12:18 UTC, nbirillo commented on src/main/kotlin/org/jetbrains/research/ml/ast/transformations/anonymization/NamedEntityKind.kt
> +        fun computeElementKind(element: PsiElement): NamedEntityKind? = when (element) {
Maybe `getElementKind`?

2020-11-17 03:39 UTC, elena-lyulina requested changes
Nice

2020-11-17 03:39 UTC, elena-lyulina commented on docs/Anonymization.md
> +  f1v1 = v1
Maybe we should have separators between the parent name and the other part to simplify reading? for example, f1_v1

2020-11-17 03:39 UTC, elena-lyulina commented on src/main/kotlin/org/jetbrains/research/ml/ast/transformations/anonymization/AnonymizationVisitor.kt
> +    private val anonymizer = ElementAnonymizer()
Let's put the properties on top of the class according to documentation https://kotlinlang.org/docs/reference/coding-conventions.html#class-layout

2020-11-18 08:02 UTC, nbirillo approved these changes
Great!

2020-11-18 14:16 UTC, elena-lyulina approved these changes

2020-11-18 14:41 UTC, merged