Comments removal transformation
JetBrains-Research/ast-transformations pull request #17
Opened 2020-11-17 14:29 UTC by nbirillo

2020-11-17 19:12 UTC, artbobrov commented
Does it work for multiline string?
For example:
```python
tmp = '''
hello
world
'''
```

2020-11-17 19:29 UTC, nbirillo commented
@artbobrov tnaks! I will fix it

2020-11-18 13:42 UTC, elena-lyulina requested changes

2020-11-18 13:42 UTC, elena-lyulina commented on src/main/kotlin/org/jetbrains/research/ml/ast/transformations/commentsRemoval/CommentsRemovalTransformation.kt
> +        acceptStatements(psiTree.project, stringLiteralExpressions, visitor)
acceptStatements(psiTree.project, comments + stringLiteralExpressions, visitor) ?

2020-11-24 11:32 UTC, elena-lyulina approved these changes
Cool

2020-11-24 11:32 UTC, merged