Apply GumTree actions to PSI
JetBrains-Research/ast-transformations pull request #29
Opened 2021-01-18 15:14 UTC by nbirillo

2021-02-01 23:00 UTC, elena-lyulina requested changes
Cool, thanks!

2021-02-02 07:19 UTC, nbirillo commented on src/main/kotlin/org/jetbrains/research/ml/ast/gumtree/diff/PsiElementTransformer.kt
> +        val nodesObserver = NodesObserver()
A field for the class? We should have a new instance of the insertedNodesIds for each call `applyAction` function, isn't it?

2021-02-02 07:22 UTC, nbirillo commented on src/test/kotlin/org/jetbrains/research/ml/ast/gumtree/diff/PsiElementTransformerTest.kt
> +        }
I thought that we would like to add an intermediate stage in which we will reorder the actions and select only N of them, so I separated these functions

2021-02-02 07:24 UTC, nbirillo commented on src/test/kotlin/org/jetbrains/research/ml/ast/gumtree/diff/PsiElementTransformerTest.kt
> +    //  and GumTree internal actions
Oh sorry, I forgot to push it. I found only one example with this problem

2021-02-04 13:56 UTC, elena-lyulina requested changes
Just one more comment

2021-02-04 13:56 UTC, elena-lyulina commented on src/main/kotlin/org/jetbrains/research/ml/ast/gumtree/diff/PsiElementTransformer.kt
> +    val insertedNodesIds: MutableSet<Int> = HashSet()
Why do we need to pass srcPsiNodes, dstPsiNodes, and insertedNodesIds to the constructor? what if we pass the wrong variables? why not make fields and count automatically?

2021-02-04 14:29 UTC, elena-lyulina approved these changes
Nice :)

2021-02-04 14:32 UTC, merged